### PR TITLE
Product relate

### PR DESCRIPTION
**Pull request by SzersCode**
@ngodinhan058  @NguyenMinhThiet @xuanloi1999  review vs merge dùm tôi !

### CODE REVIEW

**Review by NguyenMinhThiet — DISMISSED** [review]
checked

**Review by ngodinhan058 — DISMISSED** [review]
checked

**Review by ngodinhan058 — APPROVED** [review]
checked

**Review by NguyenMinhThiet — APPROVED** [review]
checked

**Pull request merged**
